### ISSUE TITLE
Remove the default namespace from the generated CRs

### ISSUE THREAD

**Issue by masayag** [parodos-dev/serverless-workflows#12]
Depends on  https://issues.redhat.com/browse/KOGITO-9990

**Comment by rgolangh** [comment]
how is kn-workflow going to help here?

**Comment by masayag** [comment]
Based on https://redhat-internal.slack.com/archives/C059YMMB664/p1705523503508229?thread_ts=1701114169.229309&cid=C059YMMB664
we added a requirement for that. however, for now, only the workflowproj supports no namespace, and the same behavior should be rolled to kn-workflow

**Comment by rgolangh** [comment]
depends on: https://issues.redhat.com/browse/KOGITO-9990
