### ISSUE TITLE
Include greeting SWF

### ISSUE THREAD

**Issue by dmartinol** [parodos-dev/serverless-workflows#3]
Greeting SWF is part of the https://github.com/parodos-dev/orchestrator-helm-chart and the image needs to be generated using the defined CI pipeline

**Comment by rgolangh** [comment]
I added greeting with this
https://github.com/rgolangh/serverless-workflows-helm/pull/11

The 2nd thing is to merge serverless-workflows-helm to parodos-dev/orchestrator-helm-chart. They are not the same although very close. (more developer/kubernetes functionality in the the former)

**Comment by rgolangh** [comment]
now we got https://github.com/rgolangh/serverless-workflows-helm/pull/12
merging soon after the image is pushed to quay

**Comment by masayag** [comment]
Closed by https://github.com/parodos-dev/serverless-workflows/actions/runs/7518017920/job/20465098576

```
✅ Successfully pushed "serverless-workflow-greeting:latest" to "quay.io/orchestrator/serverless-workflow-greeting:latest"
sha256:33b2a46374b51e7cc90b70b731d80ce94b19d6fa095b192619800ab384883720
/usr/bin/podman push --quiet --digestfile serverless-workflow-greeting-latest_digest.txt serverless-workflow-greeting:8dc7224f47325e380e72ac4555f4b2aa1d129e8a quay.io/orchestrator/serverless-workflow-greeting:8dc7224f47325e380e72ac4555f4b2aa1d129e8a --tls-verify=true --creds=***:***
✅ Successfully pushed "serverless-workflow-greeting:8dc7224f47325e380e72ac[45](https://github.com/parodos-dev/serverless-workflows/actions/runs/7518017920/job/20465098576#step:4:51)55f4b2aa1d129e8a" to "quay.io/orchestrator/serverless-workflow-greeting:8dc7224f47325e380e72ac4555f4b2aa1d129e8a"
sha256:33b2a[46](https://github.com/parodos-dev/serverless-workflows/actions/runs/7518017920/job/20465098576#step:4:52)374b51e7cc90b70b731d80ce94b19d6fa095b192619800ab384883720
```
